# ProtectedChat ${project.version} Configuration File

# =================== #
# Protectors Settings #
# =================== #

Holograms:
    # The format of the messages
    Messages Format: '&f%message%'

    # The plugin which is used to create Holograms
    Provider: HolographicDisplays