name: ProtectedChat
main: dte.protectedchat.ProtectedChat
version: ${project.version}
api-version: 1.13
description: Protects chat messages using multiple useful ways.
softdepend: [HolographicDisplays]
author: https://github.com/DavidTheExplorer
commands:
    chatprotect:
        description: Protects or disables a player's chat protection.
        aliases: [cp]